package resolvers

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.63

import (
	"context"
	"fmt"
	"iam_services_main_v1/gql/generated"
	"iam_services_main_v1/gql/models"
)

// BillingInfo is the resolver for the billingInfo field.
func (r *accountResolver) BillingInfo(ctx context.Context, obj *models.Account) (*models.BillingInfo, error) {
	panic(fmt.Errorf("not implemented: BillingInfo - billingInfo"))
}

// Account returns generated.AccountResolver implementation.
func (r *Resolver) Account() generated.AccountResolver { return &accountResolver{r} }

type accountResolver struct{ *Resolver }
